config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help', via: :get
  match '/about', to: 'static_pages#about', via: :get
  match '/contact', to: 'static_pages#contact', via: :get

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_secure_password
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6}
  validates_confirmation_of :password, if: lambda { |m| m.password.present? }


  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help

  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to the Sample App'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attributes(remember_token: User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    = link_to 'Rails Tutorial', 'http://railstutorial.org/'
  nav
    ul
      li = link_to 'About', about_path
      li = link_to 'Contact', contact_path
      li = link_to 'News', 'http://news.railstutorial.org/'

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to 'sample app', root_path, id: 'logo'
      nav
        ul.nav.pull-right
          li = link_to 'Home',    root_path
          li = link_to 'Help',    help_path
          - if signed_in?
            li = link_to 'Users', '#'
            li#fat-menu.dropdown
              = link_to 'Account <b class="caret"></b>'.html_safe, '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }
              ul.dropdown-menu
                li = link_to 'Profile', current_user
                li = link_to 'Settings', '#'
                li.divider
                li = link_to 'Sign out', signout_path, method: :delete
          - else
            li = link_to 'Sign in', signin_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    /[if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

    body
      = render 'layouts/header'
      .container
        = render 'shared/alerts'
        = yield
        = render 'layouts/footer'
        = debug(params) if Rails.env.development?
      = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/shared/_alerts.html.slim
- flash.each do |key, value|
  .alert *{class: "alert-#{key}"}
    = value

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-error
      | The form contains #{pluralize(@user.errors.count, 'error')}
    ul
      - @user.errors.full_messages.each do |msg|
        li * #{ msg }

app/views/static_pages/about.html.slim
- provide(:title, 'About Us')
h1 About Us
p
  | The #{link_to 'Ruby on Rails Tutorial', 'http://railstutorial.org' } is a project to make a book and screencasts to teach web development with
    #{ link_to 'Ruby on Rails', 'http://rubyonrails.org' }. This is the sample application for the tutorial.

app/views/static_pages/contact.html.slim
- provide(:title, 'Contact')
h1 Contact
p
  | Contact Ruby on Rails Tutorial about the sample app at the #{link_to 'contact page', 'http://railstutorial.org/contact' }.

app/views/static_pages/help.html.slim
- provide(:title, 'Help')
h1 Help
p
	| Get help on the Ruby on Rails Tutorial at the #{link_to 'Rails Tutorial help page', 'http://railstutorial.org/help' }
	| To get help on this sample app, see the #{ link_to 'Rails Tutorial book', 'http://railstutorial.org/help' }

app/views/static_pages/home.html.slim
.center.hero-unit
  h1 Welcome to the Sample App
  h2 This is the home page for the #{link_to 'Ruby on Rails Tutorial', 'http://railstutorial.org/'} sample application.
  = link_to 'Sign up now!', signup_path, class: 'btn btn-large btn-primary'

= link_to image_tag('rails.png', alt: 'Rails'), 'http://rubyonrails.org/'

app/views/users/new.html.slim
- provide(:title, 'Sign Up')
h1 Sign Up
.row
	.span6.offset3
		= form_for(@user) do |f|
		  = render 'shared/error_messages'

		  = f.label :name
		  = f.text_field  :name

		  = f.label :email
		  = f.text_field :email

		  = f.label :password
		  = f.password_field :password

		  = f.label :password_confirmation, 'Confirmation'
		  = f.password_field :password_confirmation

		  = f.submit 'Create my account', class: 'btn btn-large btn-primary'

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
	aside.span4
	  section
			h1 #{gravatar_for(@user)} #{ @user.name }